### ISSUE TITLE
Parameter 'url' must be a string, not undefined

### ISSUE THREAD

**Issue by Arkhayla** [gsingers/slack-jira-plugin#37]
Hi, I seem to get the following error no matter what I try even just a basic config
`
url.js:90
    throw new TypeError("Parameter 'url' must be a string, not " + typeof url);
`
I believe this is the pertinent error ^
Followed by this:
`TypeError: Parameter 'url' must be a string, not undefined
    at Url.parse (url.js:90:11)
    at Object.urlParse [as parse] (url.js:84:5)
    at WebSocket.initAsClient (/home/arkhayla/slack-jira-plugin/node_modules/ws/lib/WebSocket.js:550:23)
    at new WebSocket (/home/arkhayla/slack-jira-plugin/node_modules/ws/lib/WebSocket.js:74:18)
    at /home/arkhayla/slack-jira-plugin/node_modules/node-slackbot/lib/slackbot.js:93:17
    at IncomingMessage.<anonymous> (/home/arkhayla/slack-jira-plugin/node_modules/node-slackbot/lib/slackbot.js:42:18)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:441:9)`

I do have a default node configured and from what I can tell all of the information is filled in and formatted exactly the way expected (based on the example)

**Comment by devantheone** [comment]
I have the same problem.

**Comment by jaredjstewart** [comment]
Same here

**Comment by VincentFerreira** [comment]
same problem too

**Comment by merciero** [comment]
same problem as well, any lead so far?

**Comment by jtrobman** [comment]
Check your Slack token, it may be missing or needs replacing. https://api.slack.com/custom-integrations/legacy-tokens
